### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by kerim** [lucastorri/Mendeley-Importer-for-Safari#1]
How do I install this?

**Comment by kerim** [comment]
I figured it out, although it might not be the best way to do this. Go go to:

http://github.com/lucastorri/Mendeley-Importer-for-Safari/blob/master/dist/mendeleyimporterforsafari-1.0.safariextz

Control click on "raw" and save to your disk. Then double click on the file in the Safari download window. The extension works the same as the bookmarklet, so not sure if there is any reason to use it over the bookmarklet.

**Comment by lucastorri** [comment]
Thanks Kerim,

that's pretty much it about how you should install.

For me, the advantage is only to have a button in the toolbar.
